var mongoose = require('./MongoDB.js'),
    Schema = mongoose.Schema;

var PortSchema = new Schema({
    PortID: {type:Number},
    PortName: {type:String},
    GlobalPortID: {type:String},
    WorldPortNumber: {type:String},
    Country: {type:String},
    CountryCode: {type:String},
    FullPortStyle: {type:String},
    LastUpdateDate: {type:Date},
    BreakbulkFacilities: {type:Boolean},
    ContainerFacilities: {type:Boolean},
    DryBulkFacilities: {type:Boolean},
    DryDockFacilities: {type:Boolean},
    GasFacilities: {type:Boolean},
    LiquidFacilities: {type:Boolean},
    MultipurposeFacilities: {type:Boolean},
    PassengerFacilities: {type:Boolean},
    RoRoFacilities: {type:Boolean},
    CSICompliant: {type:Boolean},
    ISPSCompliant: {type:Boolean},
    LatitudeDecimal: {type:Number},
    LatitudeDegrees: {type:Number},
    LatitudeIndicator:{type:String},
    LatitudeMinutes:{type:Number},
    LongitudeDecimal: {type:Number},
    LongitudeDegrees:{type:Number},
    LongitudeIndicator:{type:String},
    LongitudeMinutes:{type:Number},
    MaxBeam:{type:Number},
    MaxLOA:{type:Number},
    MaximumDraft:{type:Number},
    Status:{type:String},
    TimeZone:{type:String},
    UNLOCODE:{type:String},
},{ collection: "ports"});

module.exports =  mongoose.model('Port',PortSchema);
